language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - "npm run ci"
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    master: true
